INSERT INTO purchases VALUES (1002,'Sacramento','CA','Nylon Tackle Bag','Fishing',59);
INSERT INTO purchases VALUES (1003,'Evansville','IN','River Raincoat','Apparel',130);
INSERT INTO purchases VALUES (1004,'Evansville','IN','River Raincoat','Apparel',130);
INSERT INTO purchases VALUES (1005,'Toronto','ON','Polarized Sunglasses','Apparel',39);
INSERT INTO purchases VALUES (1006,'Meridian','ID','River Raincoat','Apparel',130);
INSERT INTO purchases VALUES (1007,'Fort Collins','CO','River Raincoat','Apparel',130);
INSERT INTO purchases VALUES (1008,'Indianapolis','IN','30mm Rifle Scope','Firearms',409);
INSERT INTO purchases VALUES (1009,'Hillsboro','OR','Waders','Fishing',52);
INSERT INTO purchases VALUES (1010,'Des Moines','IA','Bolt-action .22 Rifle','Firearms',299);
INSERT INTO purchases VALUES (1011,'Tacoma','WA','River Raincoat','Apparel',130);
INSERT INTO purchases VALUES (1012,'New Orleans','LA','Bolt-action .22 Rifle','Firearms',239);
INSERT INTO purchases VALUES (1013,'Memphis','TN','Wood-grip 1911 Pistol','Firearms',1099);
INSERT INTO purchases VALUES (1014,'Atlanta','GA','River Kayak','Boating',349);
INSERT INTO purchases VALUES (1015,'South Burlington','VT','Baitcasting Rod Combo','Fishing',99);
INSERT INTO purchases VALUES (1016,'Owensboro','KY','Reaction Hiking Boots','Apparel',129);
INSERT INTO purchases VALUES (1017,'Chandler','AZ','Sea Kayak','Boating',449);
INSERT INTO purchases VALUES (1018,'Paradise','NV','River Raincoat','Apparel',104);
INSERT INTO purchases VALUES (1019,'Honolulu','HI','Quad-prop Camera Drone','Other',149);
INSERT INTO purchases VALUES (1020,'Bridgeport','CT','Wood-grip 1911 Pistol','Firearms',879);
INSERT INTO purchases VALUES (1021,'Denver','CO','Classic Fly Rod and Reel','Fishing',129);
INSERT INTO purchases VALUES (1022,'Honolulu','HI','Rugged Sport Sandals','Apparel',129);
INSERT INTO purchases VALUES (1023,'Laramie','WY','Polarized Sunglasses','Apparel',31);
INSERT INTO purchases VALUES (1024,'Cambridge','MA','EZ-Conceal Holster','Firearms',49);
INSERT INTO purchases VALUES (1025,'Bloomington','MN','River Kayak','Boating',349);
INSERT INTO purchases VALUES (1026,'Aurora','CO','Wood-grip 1911 Pistol','Firearms',1099);
INSERT INTO purchases VALUES (1027,'Chandler','AZ','Sonar/GPS Combo','Fishing',999);
INSERT INTO purchases VALUES (1028,'Akron','OH','EZ-Conceal Holster','Firearms',39);
INSERT INTO purchases VALUES (1029,'Hattiesburg','MS','Self-inflating Lifejacket','Boating',169);
INSERT INTO purchases VALUES (1030,'Houston','TX','Sea Kayak','Boating',449);
INSERT INTO purchases VALUES (1031,'Ketchikan','AK','Reaction Hiking Boots','Apparel',129);
INSERT INTO purchases VALUES (1032,'Knoxville','TN','Quad-prop Camera Drone','Other',149);
INSERT INTO purchases VALUES (1033,'Saint Paul','MN','River Raincoat','Apparel',130);
INSERT INTO purchases VALUES (1034,'Harrisburg','PA','Sonar/GPS Combo','Fishing',999);
INSERT INTO purchases VALUES (1035,'Baton Rouge','LA','Classic Fly Rod and Reel','Fishing',129);
INSERT INTO purchases VALUES (1036,'Auburn','ME','Wrinkle-free Shirt','Apparel',39);
INSERT INTO purchases VALUES (1037,'Shreveport','LA','Sonar/GPS Combo','Fishing',999);
INSERT INTO purchases VALUES (1038,'Iowa City','IA','Polarized Sunglasses','Apparel',39);
INSERT INTO purchases VALUES (1039,'Great Falls','MT','Wood-grip 1911 Pistol','Firearms',1099);
INSERT INTO purchases VALUES (1040,'Anchorage','AK','Wood-grip 1911 Pistol','Firearms',1099);
INSERT INTO purchases VALUES (1041,'Allentown','PA','Bolt-action .22 Rifle','Firearms',299);
INSERT INTO purchases VALUES (1042,'Lincoln','NE','Logo Tee','Apparel',19);
INSERT INTO purchases VALUES (1043,'Reno','NV','Classic Fly Rod and Reel','Fishing',103);
INSERT INTO purchases VALUES (1044,'Louisville','KY','Quad-prop Camera Drone','Other',119);
INSERT INTO purchases VALUES (1045,'Fairbanks','AK','Waders','Fishing',65);
INSERT INTO purchases VALUES (1046,'Iowa City','IA','Sonar/GPS Combo','Fishing',999);
INSERT INTO purchases VALUES (1047,'Detroit','MI','Sonar/GPS Combo','Fishing',799);
INSERT INTO purchases VALUES (1048,'Cheyenne','WY','Expedition Cooler','Other',200);
INSERT INTO purchases VALUES (1049,'Clarksville','TN','Nylon Tackle Bag','Fishing',59);
INSERT INTO purchases VALUES (1050,'Harrisburg','PA','Self-inflating Lifejacket','Boating',169);
INSERT INTO purchases VALUES (1051,'Glendale','AZ','Waders','Fishing',65);
INSERT INTO purchases VALUES (1052,'Overland Park','KS','Baitcasting Rod Combo','Fishing',99);
INSERT INTO purchases VALUES (1053,'Sterling Heights','MI','Logo Tee','Apparel',24);
INSERT INTO purchases VALUES (1054,'Owensboro','KY','Sea Kayak','Boating',449);
INSERT INTO purchases VALUES (1055,'Rockville','MD','Expedition Cooler','Other',250);
INSERT INTO purchases VALUES (1056,'Erie','PA','Logo Tee','Apparel',24);
INSERT INTO purchases VALUES (1057,'Independence','MO','Waders','Fishing',65);
INSERT INTO purchases VALUES (1058,'Minneapolis','MN','Wrinkle-free Shirt','Apparel',39);
INSERT INTO purchases VALUES (1059,'Kaneohe','HI','River Kayak','Boating',279);
INSERT INTO purchases VALUES (1060,'Fayetteville','AR','River Kayak','Boating',349);
INSERT INTO purchases VALUES (1061,'Springfield','MO','Bolt-action .22 Rifle','Firearms',299);
INSERT INTO purchases VALUES (1062,'Cincinnati','OH','EZ-Conceal Holster','Firearms',49);
INSERT INTO purchases VALUES (1063,'Saint Louis','MO','Wrinkle-free Shirt','Apparel',39);
INSERT INTO purchases VALUES (1064,'Eugene','OR','EZ-Conceal Holster','Firearms',39);
INSERT INTO purchases VALUES (1065,'Metairie','LA','Quad-prop Camera Drone','Other',149);
INSERT INTO purchases VALUES (1066,'Tuscaloosa','AL','EZ-Conceal Holster','Firearms',49);
INSERT INTO purchases VALUES (1067,'Huntsville','AL','Reaction Hiking Boots','Apparel',129);
INSERT INTO purchases VALUES (1068,'Tacoma','WA','Classic Fly Rod and Reel','Fishing',129);
INSERT INTO purchases VALUES (1069,'Kaneohe','HI','Bolt-action .22 Rifle','Firearms',299);
INSERT INTO purchases VALUES (1070,'Broken Arrow','OK','30mm Rifle Scope','Firearms',409);
INSERT INTO purchases VALUES (1071,'Milwaukee','WI','Bolt-action .22 Rifle','Firearms',299);
INSERT INTO purchases VALUES (1072,'Metairie','LA','Logo Tee','Apparel',24);
INSERT INTO purchases VALUES (1073,'Spokane','WA','Wood-grip 1911 Pistol','Firearms',1099);
INSERT INTO purchases VALUES (1074,'Gresham','OR','Quad-prop Camera Drone','Other',149);
INSERT INTO purchases VALUES (1075,'Los Angeles','CA','EZ-Conceal Holster','Firearms',39);
INSERT INTO purchases VALUES (1076,'Kaneohe','HI','EZ-Conceal Holster','Firearms',49);
INSERT INTO purchases VALUES (1077,'Juneau','AK','Waders','Fishing',52);
INSERT INTO purchases VALUES (1078,'Dallas','TX','Nylon Tackle Bag','Fishing',59);
INSERT INTO purchases VALUES (1079,'Kenosha','WI','Self-inflating Lifejacket','Boating',169);
INSERT INTO purchases VALUES (1080,'Newark','DE','Reaction Hiking Boots','Apparel',129);
INSERT INTO purchases VALUES (1081,'Gary','IN','Classic Fly Rod and Reel','Fishing',129);
INSERT INTO purchases VALUES (1082,'South Portland','ME','30mm Rifle Scope','Firearms',409);
INSERT INTO purchases VALUES (1083,'Bridgeport','CT','Sonar/GPS Combo','Fishing',999);
INSERT INTO purchases VALUES (1084,'Jefferson City','MO','Polarized Sunglasses','Apparel',39);
INSERT INTO purchases VALUES (1085,'Cambridge','MA','Sonar/GPS Combo','Fishing',999);
INSERT INTO purchases VALUES (1086,'Madison','WI','Rugged Sport Sandals','Apparel',129);
INSERT INTO purchases VALUES (1087,'Bangor','ME','River Raincoat','Apparel',104);
INSERT INTO purchases VALUES (1088,'Rutland','VT','Wood-grip 1911 Pistol','Firearms',1099);
INSERT INTO purchases VALUES (1089,'Carson City','NV','Wrinkle-free Shirt','Apparel',39);
INSERT INTO purchases VALUES (1090,'Norman','OK','Rugged Sport Sandals','Apparel',129);
INSERT INTO purchases VALUES (1091,'Wilmington','DE','30mm Rifle Scope','Firearms',409);
INSERT INTO purchases VALUES (1092,'Spokane','WA','Expedition Cooler','Other',200);
INSERT INTO purchases VALUES (1093,'Baltimore','MD','Bolt-action .22 Rifle','Firearms',239);
INSERT INTO purchases VALUES (1094,'Indianapolis','IN','30mm Rifle Scope','Firearms',409);
INSERT INTO purchases VALUES (1095,'Lafayette','LA','Logo Tee','Apparel',24);
INSERT INTO purchases VALUES (1096,'Rockford','IL','Baitcasting Rod Combo','Fishing',99);
INSERT INTO purchases VALUES (1097,'Atlanta','GA','Reaction Hiking Boots','Apparel',129);
INSERT INTO purchases VALUES (1098,'Jefferson City','MO','Expedition Cooler','Other',200);
INSERT INTO purchases VALUES (1099,'Duluth','MN','Reaction Hiking Boots','Apparel',129);
INSERT INTO purchases VALUES (1100,'Minneapolis','MN','Rugged Sport Sandals','Apparel',129);
INSERT INTO purchases VALUES (1101,'Columbus','OH','Sea Kayak','Boating',359);
